export const themes = {
  sunset: {
    id: 'sunset',
    name: 'Sunset Editorial',
    colors: {
      '--cream': '#fff4eb',
      '--white': '#fffdf8',
      '--black': '#1f1726',
      '--brown': '#ff6b57',
      '--brown-light': '#ff9d7b',
      '--brown-pale': '#ffd7c6',
      '--gray': '#6f5c67',
      '--gray-light': '#f1d9cf',
      '--accent-strong': '#ff8a3d',
      '--accent-soft': '#ffe6d7',
      '--surface-dark': '#241826',
      '--surface-dark-soft': '#3b293e',
      '--hero-glow': 'rgba(255, 133, 102, 0.28)',
    },
  },
  citrus: {
    id: 'citrus',
    name: 'Electric Citrus',
    colors: {
      '--cream': '#f6ffe5',
      '--white': '#ffffff',
      '--black': '#13261a',
      '--brown': '#00a86b',
      '--brown-light': '#7de27b',
      '--brown-pale': '#d8f5c5',
      '--gray': '#486053',
      '--gray-light': '#e8f8de',
      '--accent-strong': '#f4b400',
      '--accent-soft': '#fff4b8',
      '--surface-dark': '#11241b',
      '--surface-dark-soft': '#1d3b2d',
      '--hero-glow': 'rgba(125, 226, 123, 0.24)',
    },
  },
  noir: {
    id: 'noir',
    name: 'Rose Noir',
    colors: {
      '--cream': '#fff5f7',
      '--white': '#ffffff',
      '--black': '#1f1020',
      '--brown': '#d6417a',
      '--brown-light': '#f08db2',
      '--brown-pale': '#f5cfdd',
      '--gray': '#705565',
      '--gray-light': '#f5e2e9',
      '--accent-strong': '#7c3aed',
      '--accent-soft': '#f7d8ef',
      '--surface-dark': '#221126',
      '--surface-dark-soft': '#3c1d42',
      '--hero-glow': 'rgba(214, 65, 122, 0.22)',
    },
  },
}

export const defaultThemeId = 'noir'
